apiVersion: v1
name: centrifugo
description: Centrifugo is a scalable real-time messaging server in language-agnostic way
version: 6.1.0
appVersion: 2.8.6
home: https://centrifugal.github.io/centrifugo/
icon: https://centrifugal.github.io/centrifugo/images/favicon.png
maintainers:
  - name: FZambia
    email: frvzmb@gmail.com
engine: gotpl
