apiVersion: v1
name: centrifugo
description: Centrifugo is a scalable real-time messaging server in language-agnostic way
version: 9.0.4
appVersion: 4.0.2
home: https://centrifugal.dev
icon: https://centrifugal.dev/img/favicon.png
maintainers:
  - name: FZambia
    email: frvzmb@gmail.com
engine: gotpl
