name: Helm Chart CI

on: [push, pull_request]

jobs:
  lint-and-install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Test minimum supported version and latest stable
        k8s-version:
          - v1.21.14  # Test on minimum supported
          - v1.35.0   # And modern one
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Install chart-testing
        uses: helm/chart-testing-action@v2.7.0

      - name: Run chart-testing (lint)
        run: ct lint --config ct.yaml

      - name: Create kind cluster (Kubernetes ${{ matrix.k8s-version }})
        uses: helm/kind-action@v1.12.0
        with:
          node_image: kindest/node:${{ matrix.k8s-version }}

      - name: Run chart-testing (install)
        run: ct install --config ct.yaml
